### ISSUE TITLE
FileNotFound exception: settings/info.txt (No such file or directory)

### ISSUE THREAD

**Issue by dtaillard** [FlowingMedia/TimeFlow#27]
When I run Timeline.jar with `$ java -jar Timeline.jar`, a FileNotFound exception is thrown because settings/info.txt does not exist.  My system is running linux, and my java version is "1.8.0_51".  I am using Timeflow version 0.5.

```
java.io.FileNotFoundException: settings/info.txt (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at java.io.FileReader.<init>(FileReader.java:58)
        at timeflow.util.IO.lines(IO.java:12)
        at timeflow.app.AppState.<init>(AppState.java:17)
        at timeflow.app.TimeflowApp.<init>(TimeflowApp.java:35)
        at timeflow.app.TimeflowAppLauncher.main(TimeflowAppLauncher.java:25)
```

**Comment by beginneer** [comment]
did you solve it  ?

**Comment by dtaillard** [comment]
@beginneer There is no "settings/info.txt" file included anywhere in the ZIP file that I downloaded, so I can't fix it. I could create the file myself, but I don't know what the contents of the file should be.
